### ISSUE TITLE
DOM events should be processed from inner to outer component

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-dom#101]
Currently the order in which listeners are notified depends on the order they are attached.

If we have one parent component P and one child component C and both components create streams of click events `DOM.select(':root').events('click')` it might occur that the parent component P get's notified of a click before the child C get's notified.
The order is determined by which stream get's subscribed first.

The correct bubbling behavior would be to notify the child component first. So the child component can have a chance to stop the event's propagation and prevent the parent from getting the event.

If `useCapture` is set to true the order should be inverted: If both components set useCapture to true the parent should always be notified first.

**Comment by staltz** [comment]
Fully agreed

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#229
