### ISSUE TITLE
<video> "timeupdate" event is not handled

### ISSUE THREAD

**Issue by iambumblehead** [cyclejs/cycle-dom#103]
<video> "timeupdate" event is not handled
```javascript
sources.DOM.select('#videoelem').events('timeupdate') // no data
```

The workaround I'm using involves rx-dom
```javascript
rx.DOM.fromEvent(document.getElementById('videoelem'), 'timeupdate'); // data!
```

`timeupdate` is [non-bubbling][0]

[0]: https://developer.mozilla.org/en-US/docs/Web/Events/timeupdate

**Comment by staltz** [comment]
Fixed in version 9.0.3
