### ISSUE TITLE
mockDOMSource and observable

### ISSUE THREAD

**Issue by chadrien** [cyclejs/cycle-dom#106]
Hi,

I wonder if it would be possible to mock a `select()`'s `observable` as well as its `event()`. I just encountered a case where I needed to use `DOM.select('…').observable` and doing the mock by hand made me sad :cry: 

If you want me to do a PR I'd be glad to, we'd just have to discuss how to approach this (use an `observable` key just like the events, split a selector to an object of `{ observable: Rx.Observable.just(), events: { click: Rx.Observable.just() } }`, something else…)

**Comment by staltz** [comment]
I mostly agree with you. Thanks for the suggestion. Your suggestion would be a breaking change, though (not nice. but sometimes necessary). How about this instead?

```js
const userEvents = mockDOMSource({
  '.foo': {
    'click': Rx.Observable.just({target: {}}),
    'mouseover': Rx.Observable.just({target: {}}),
    observable: Rx.Observable.empty() // <---- this
  },
  '.bar': {
    'scroll': Rx.Observable.just({target: {}})
  }
});
```
I doubt there will ever be an event called `'observable'` that would make this be a naming conflict. 

Do you agree?
Ping also @TylorS.

A PR would be nice. :)

**Comment by chadrien** [comment]
Yeah, that's what I meant by

> use an observable key just like the events

I totally agree that chances are low that an event would be called `observable`, and it seems the most simple/non breaking solution to me

**Comment by TylorS** [comment]
@staltz I think that your proposed solution looks simple enough.

**Comment by staltz** [comment]
Done in v9.1.0, thanks @chadrien !

**Comment by chadrien** [comment]
:tada:

**Comment by TylorS** [comment]
@chadrien I copied your work and it's also in motorcycle-dom v1.2.0

**Comment by TylorS** [comment]
Also in v1.1.0 of cycle-snabbdom :+1:
