### ISSUE TITLE
CamelCase issue with SVG

### ISSUE THREAD

**Issue by jbremmer** [cyclejs/cycle-dom#109]
So I'm trying to inline an SVG in my DOM, when I do that viewBox attribute get's rendered to 'viewbox' which makes SVG invisible.

Does anyone know a way around this or is it I'm doing something wrong?

**Comment by TylorS** [comment]
Are you using the `svg()` helper function?
```js
import {svg} from '@cycle/dom'
```
If so, how are you using it?

**Comment by jbremmer** [comment]
Here's my snippet:

`h("svg", {
                "attributes": {
                  "x": "0px",
                  "y": "0px",
                  "viewBox": "0 0 100 100",
                  "space": "preserve",
                  "class": "W(25px) H(25px)"
                }
              }, [
                h('g.art', [
                  h("path", {
                    "attributes": {
                      "d": "M86.5,53v-6c0-2.961-0.359-3.5-3.5-3.5H56.5V17c0-2.961-0.48-3.5-3.5-3.5h-6c-3.1,0-4.5,0.539-4.5,3.5v26.5   H15c-2.961,0-4.5,0.48-4.5,3.5v6c0,3.1,1.539,4.5,4.5,4.5h27.5V85c0,3.02,1.461,4.5,4.5,4.5h6c2.961,0,3.5-1.359,3.5-4.5V57.5H83   C86.02,57.5,86.5,56.039,86.5,53z"
                    }
                  })
                ])
              ])`

**Comment by TylorS** [comment]
You'll want to replace all of the `h()`s with `svg()`

**Comment by TylorS** [comment]
Just the ones that are for SVGs of course.

**Comment by jbremmer** [comment]
Works like a charm, thank you, I misunderstood the purpose of svg in cycle/dom

**Comment by TylorS** [comment]
No problem. :+1:
