### ISSUE TITLE
Optimize interactions.get querySelectors

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#11]
_From @staltz on May 7, 2015 6:47_

We can avoid querySelector by tapping into diff/patch to know exactly which elements were added or modified. Based on interactions.get(selector, eventType), we build a Map of selector/eventType to event Subjects, we give that Map to our modified diff/patch process which will filter the Map and return a subset of the DOM containing only those elements that need to be refreshed with regard to listeners supposed to be attached to them. Then we won't need to do querySelector at all, because diff/patch will return us those DOM elements, we just need to attach listeners.

Roughly:
```haskell
render :: VirtualDom -> VirtualDom -> Dom -> Dom
render new old oldDom = newDom

render :: VirtualDom -> VirtualDom -> Dom -> Map Selector DomElement -> (Dom, Map Selector DomElement)
```

_Copied from original issue: cyclejs/cycle-core#115_

**Comment by TylorS** [comment]
@staltz I'm going to close this since we've worked through event delegation. If you feel this should remain open, of course feel free to reopen.

**Comment by staltz** [comment]
Yeah
