### ISSUE TITLE
interactions.get() should respect scope of child custom element 

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#13]
_From @staltz on March 17, 2015 8:37_

Currently, `User.event$('.foo', 'click')` selects all `.foo` under the User's root node, including `.foo` which lives inside a custom element. We don't want the querySelector to look inside child custom elements. We might need to use the Shadow DOM (the polyfill?) for that. Or, as a shotgun solution, just make all Cycle custom elements become full-blown web components. That would be a nice side benefit of fixing this bug.

_Copied from original issue: cyclejs/cycle-core#84_

**Comment by staltz** [comment]
_From @erykpiast on March 17, 2015 8:48_

That's the thing!

Why, in my opinion, turning towards Web Components makes sense:

 * it's well known and (almost?) standardized concept
 * it helps with creating universal and portable components based on the framework, which implicates its popularization
 * it's apparently the future - at least in Google team's opinion (Angular 2.0 and Polymer are looking from behind the corner)
 * it solves all issues with component isolation; not only accidental selecting component's DOM from outside of it, but also events bubbling from inside to outside world; CSS isolation may be important too, especially if you don't use inline styles only

Cons:

 * it forces usage of not-so-light-or-efficient polyfills for older browsers (should we care? I guess it's a time to make a decision, if Cycle is a framework for now and here production-ready apps or for the future)
 * it limits flexibility (but to reasonable level, I think)

**Comment by staltz** [comment]
_From @ivan-kleshnin on March 22, 2015 18:8_

@erykpiast what's the size of Web Component polyfills? Do you tried them in practice?

**Comment by staltz** [comment]
_From @erykpiast on March 22, 2015 19:58_

They are (or it is actually - http://webcomponents.org/) quite big - 105 kB minified, 31 kB gzipped. Sounds scary, I know, but it always depends. Anyone, who wants to use Polymer on production, has to use it, for example. We wouldn't be alone :)

What is worth to notice, we probably don't need all Web Components parts - only Custom Elements and Shadow DOM. I can't imagine, how we can use Templates with VirtualDOM (but it would be awesome), HTML Imports aren't required at all. So, we need at least ~80 kB (~24 kB gzipped) of polyfills - 9.9 kB (3.7 kB) for Custom Elements and 69 kB (20 kB) for Shadow DOM.

**Comment by staltz** [comment]
I'm trying not to optimize for size first. So much can change in the near future, that it really isn't the biggest concern at the moment. I am a bit disturbed with the size of RxJS, but that doesn't stop me from adding it to Cycle. Shrinking down that size should come after API design.

Then there is also HTTP2 which will improve performance so much that these kB won't become a problem. And also Shadow DOM is supposed to be implemented natively in browsers so we won't be needing that polyfill forever either.

**Comment by staltz** [comment]
_From @erykpiast on March 22, 2015 22:21_

:+1:

**Comment by staltz** [comment]
_From @ivan-kleshnin on March 27, 2015 11:19_

If we have registered custom element `Picture` shouldn't 
```javascript
User.event$("Picture", "click").subscribe(() => console.log("Picture.click!");
```
also work? Now it doesn't and it looks like a bug.

**Comment by staltz** [comment]
event$() selector is much weaker than document.querySelectorAll(). I recommend using only classnames as selectors, but it's a good point that probably anything else should be supported (ids and tagnames). This will probably be fixed. :+1:

**Comment by staltz** [comment]
This issue might not be relevant anymore if we build https://github.com/staltz/cycle/issues/115

**Comment by staltz** [comment]
_From @arlair on June 6, 2015 16:23_

It looks like you don't need Shadow DOM, but if you go down the road there is a cut down version called Shady DOM. Shady DOM is used by Polymer.

https://www.polymer-project.org/1.0/articles/shadydom.html

**Comment by Frikki** [comment]
Please don’t include any polyfills for Web Components. Such includes should be left for the developers to decide. Relying on polyfills "forces" developers to program according to that polyfill, and it should be noted that the [major browser vendors have not agreed on a common API](https://hacks.mozilla.org/2015/06/the-state-of-web-components/).

**Comment by erykpiast** [comment]
:+1:
