### ISSUE TITLE
Use custom element definition fn in virtual-hyperscript

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#17]
Experiment with the possibility of importing a CE and using it, rather than globally registering it.

```js
function myCustomElem(resp) {
  // ...
  return reqs;
}

// ...
h(myCustomElem, {propFoo: 'luls'})
```

Potential problems: `myCustomElem` doesn't receive the DOM Driver's registered name in this use case.

**Comment by TylorS** [comment]
Also closing because there are no longer custom elements.
