### ISSUE TITLE
Examples on animation

### ISSUE THREAD

**Issue by Willmo36** [cyclejs/cycle-dom#18]
This might be more of a virtual-dom issue, but I think it's worth documenting animation for custom widgets. Mithril has a great write-up (http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html) on how to use velocity.js with it's vdom. The exit animations section is particularly interesting.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#218
