### ISSUE TITLE
Use requestAnimationFrame

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#28]
https://github.com/cyclejs/cycle-core/issues/100

**Comment by drewdeal** [comment]
Looking forward to this being in place. :-0

**Comment by dmitriid** [comment]
This might be of relevance: https://github.com/Matt-Esch/virtual-dom/wiki  see main-loop: Batch virtual DOM changes. Update the virtual tree at most once per request animation frame.

This is probably the most important element when people talk about requestAnimationFrame. It's quite possible it would be "enough" to use main-loop in Cycle.

P.S. No doubt, you have already looked at this :)
P.P.S. No doubt, integrating this might not be simple or enough

**Comment by ckknight** [comment]
I accomplished this on my project by doing

```js
return {
    DOM: vTree$
      .sample(0, requestAnimationFrameScheduler)
};
```

Where the requestAnimationFrameScheduler schedules the next immediate event with `requestAnimationFrame`.

**Comment by staltz** [comment]
:+1:

**Comment by ryanhiebert** [comment]
@ckknight: Very interesting. Is that just this, which I gleaned from https://gist.github.com/JesterXL/66a4d42f756272dcc8d8?

```js
requestAnimationFrameScheduler = stream.observeOn(Rx.Scheduler.requestAnimationFrame)
```

**Comment by ryanhiebert** [comment]
Or I guess it's probably just

```js
requestAnimationFrameScheduler = Rx.Scheduler.requestAnimationFrame
```

**Comment by Frikki** [comment]
So we require RxJS-DOM?

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#220
