### ISSUE TITLE
h() doesn't pass in data- attributes (or arbitrary attributes in general)

### ISSUE THREAD

**Issue by Zacqary** [cyclejs/cycle-dom#29]
Using either `h()` or `hJSX`:

```
h('div', {'data-something': 'something'})
```
or
```
<div data-something="something"></div>
```

does not pass the `data-something` attribute to the element.

I haven't gotten anything besides `className` and `id` to work, for that matter. `role` also fails to show up.

This is confusing because I don't remember having this problem using hyperscript by itself.

**Comment by staltz** [comment]
```
h('div', {attributes: {'data-something': 'something'}})
```

**Comment by Zacqary** [comment]
Sorry about that, my mistake. It definitely works with `h()`. hJSX still doesn't work, though.

**Comment by staltz** [comment]
```
<div attributes={{'data-something': 'something'}}></div>
```

**Comment by Zacqary** [comment]
Ahh, I see. I'm used to being able to insert attributes directly in React. Thank you!

**Comment by tudorilisoi** [comment]
@Zacqary :
Works with hJSX and es6 template strings (note the backticks and the use of attributes instead of className)

```jsx
var errorClass = a > 0 ?  'error' : ''';
 return (
        <div attributes={{class:`ui form success centered hello-form ${errorClass}`}} >         
        </div>
      );
```
