### ISSUE TITLE
ES6 tagged template literals for virtual-hyperscript

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#31]
**Discussion of an idea for a useful utility library that could be built separate to Cycle.js**.

Idea is given:
```js
let element = html`
  <section>
    <h1>Hello, ${name}!</h1>
  </section>
`;
```
be transformed (be equivalent) to
```js
let element = h('section', [
  h('h1', `Hello, ${name}`)
]);
```

**Comment by ohanhi** [comment]
That seems really nice!

Just to note here, this does a similar transform for JSX:
https://github.com/andreypopp/es6-template-strings-jsx/

**Comment by staltz** [comment]
I think this gist gives a pretty accurate draft of what such repo would look like for virtual-hyperscript: https://gist.github.com/lygaret/a68220defa69174bdec5

**Comment by staltz** [comment]
We are using hyperscript-helpers in 8.0.0-rc2, so this issue is obsolete.
