### ISSUE TITLE
regarding responses.props

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#32]
I really don’t know if this is the right place to ask, but when I make a custom element, which takes a `responses` argument in its "constructor" function. I can access all props with `responses.props.getAll()`, which returns a stream of props as objects. Now, assume I want to add properties to the props object. How would I go about doing that? I want to have either a new stream with the modified props object, or the modified props object added to the original stream.

I know this related more to Rx than cycle-dom, but I have searched the Interwebs, stackoverflow, etc., without any luck.

**Comment by staltz** [comment]
> returns a stream of props as objects. Now, assume I want to add properties to the props object.

> returns a **stream**... I want to add

You can't add anything to a stream.

> I want to have either a new stream with the modified props object

Yes, that's how you do it.

```js
responses.props.getAll().map(oldProps => {
  oldProps.newProp = 'foo'; // mutation, but does the job
  return oldProps;
});
```
