### ISSUE TITLE
DOM.get weird behavior with class selector name

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#33]
In my `intent` function, I want to capture focus and blur events, which I do with the following code:

```javascript
function intent(DOM) {
  return {
    isFocused$ = Rx.Observable.merge(
      DOM.get('.molecule', 'focus').map(() => true),
      DOM.get('.molecule', 'blur').map(() => false)
    ),
    value$: DOM.get('.molecule', 'input').map(e => e.target.value)
  };
}

// model left out for simplicity

function view(state$) {
  return state$.map(state => {
    ...
    return h('input.molecule');
  });
}
```

The weird part is, that `value$` works fine, but `isFocused$` doesn’t. However, if I change the class name to anything but `.molecule`, it works! But the most peculiar is that if I change the class name to, for example, `.cp-molecule-input`, it doesn’t work. Note that `value$` keeps working in spite of `molecule` being part of the class name, but not `isFocused$`.

**Update**

I think I found the issue which my sample code doesn’t illustrate. If the selector, e.g., `.molecule` is part of the class name of a parent element, e.g., `.my-molecule-container`, the `isFocused$` won’t work.

This wont work:

```javascript
...
return h('div.my-molecule-container', [
  h('input.molecule')
])
...
```

I think the problem is with line 151 in `src/render-dom.js`

```javascript
if (rootElem.className.search(new RegExp(`\\b${klass}\\b`)) >= 0) {
```

**Comment by staltz** [comment]
Yeah, this looks like a legit code, and the line you pointed out is not something I've been proud of. I'll make some tests and look for a proper solution. Thanks for the detailed report. :+1:

**Comment by staltz** [comment]
@Frikki I tested with this minimal example and I did not encounter the bug you described:

```js
function main(responses) {
  let requests = {
    DOM: responses.DOM.get('.foo', 'change')
      .map(ev => ev.target.checked)
      .startWith(false)
      .map(toggled =>
        h('div.my-foo-bar', [
          h('input.foo', {type: 'checkbox'}), 'Toggle me',
          h('p', toggled ? 'ON' : 'off')
        ])
      )
  };
  return requests;
}
```

That is, `responses.DOM.get('.foo', 'change')` returns change events happening specifically on `<input class="foo" type="checkbox">`.

**Comment by Frikki** [comment]
That’s strange. Let me dig a bit more into this.

**Comment by Frikki** [comment]
I’m going to close this issue, I don’t know what happened back then. Things are working as expected.
