### ISSUE TITLE
custom element not updated on className change

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#34]
```javascript
// in vtree
h('my-custom-element' {className: isFocused})
```

When the variable `isFocused` changed, `my-custom-element` is not updated with the change, **unless** `my-custom-element` specifically includes the property in its render:

```javascript
// in my-custom-element vtree
h('div.my-custom-element-class', {className}, children)
```

Because `className` is initially and automatically added to the element, i.e., creating _state_, I would have expected a _state change_ to automatically be reflected, too. If this isn’t _supposed_ to be the case, I would suggest this to be emphasized in the documentation.

**Comment by staltz** [comment]
When you say "`isFocused` changed", do you mean it's actually a mutable variable which you changed?

**Comment by Frikki** [comment]
Let me provide you with some sample code.

```javascript
function intent(DOM) {
  return {
    isFocused$: Rx.Observable.merge(
      DOM.get(selector, `focus`).map(() => true),
      DOM.get(selector, `blur`).map(() => false)
    ),
    ...
  };
}

function model(context, actions) {
  ...
  const isFocused$ = actions.isFocused$.startWith(false).map(
    isFocused => isFocused ? `is-focused` : ``
  );
  
  return Rx.Observable.combineLatest(
    props$,
    isFocused$,
    (props, isFocused) => ({props, isFocused})
  );
}

function view(state$) {
  return state$.map(state => {
    const {isFocused} = state;
    
    return h(`div`, [
      h('my-custom-element' {className: isFocused})
    ]);
  });
}
...
// You know the recipe ;)
```

As you can see, `isFocused` is derived through the user’s intent, which delivers a stream of `true` and `false` values, which in return is transformed in the `model` to a class name as state in the variable `isFocused`.

**Comment by staltz** [comment]
Some guesses:

Are you aware you missed a comma here?
```js
h('my-custom-element' {className: isFocused})
```

> Because className is initially and automatically added to the element, i.e., creating state

What do you mean? "Initially" / "automatically" / "create state" are alien concepts to me.

> h('my-custom-element', {className: isFocused})

If you do not use className inside the definition of the custom element, then that custom element's functionality **does not depend** on the given className parameter, hence it will not recalculate anything. This is basic RxJS: Observables are lazy, and subscribing to an Observable "turns on" the whole chain of Observables.

For example:

```js
var stream1 = Rx.Observable.interval(1000)
  .map(i => i*10)
  .do(x => console.log(x)); // will happen

var stream2 = stream1.filter(x => x !== 20);

stream.subscribe();
```

and


```js
var stream1 = Rx.Observable.interval(1000)
  .map(i => i*10)
  .do(x => console.log(x)); // will NOT happen

var stream2 = stream1.filter(x => x !== 20);

// no more subscribe
// stream.subscribe();
```

**Comment by Frikki** [comment]
> Are you aware you missed a comma here?

Typo in the sample code.

> What do you mean? "Initially" / "automatically" / "create state" are alien concepts to me.

By initially, I mean that on the first (initial) render, virtual-hyperscript applies the property `className` as `class` attribute to the `selector`. By automatically, I mean that virtual-hyperscript does this _without_ any further instructions. By create state, I mean that the returned DOM tree from virtual-hyperscript has state, i.e., virtual-hyperscript,  according to its input, creates the state of DOM tree.

> If you do not use className inside the definition of the custom element, then that custom element's functionality does not depend on the given className parameter, hence it will not recalculate anything. 

But virtual-hyperscript _does_ use the property `className`.

> Observables are lazy

Yes :) Very lazy.

**Comment by staltz** [comment]
Ah, so you mean that it's fine if we would be talking about `h('my-custom-element', {foo: isFocused})`, but when it comes to `h('my-custom-element', {className: isFocused})`, you want the className to be automatically applied to whatever is the top-level element exported by vtree$ inside the custom element definition?

**Comment by Frikki** [comment]
Yes, because initially `className` is applied, it is just not updated as other properties are (e.g., `value`). For that to happen, you need to explicitly set it on the top-level element exported by vtree$ inside the custom element definition.

**Comment by staltz** [comment]
I'm tagging this as feature, not a bug, because by default everything that is given to the custom element as props should be manually manipulated inside the custom element definition, but I'll try to open an exception for className.

May I ask also, why not just use 
```js
h(`my-custom-element.${isFocused}`)
```

**Comment by Frikki** [comment]
Because I am still too attached to older ES syntax by habit. Trying to overcome it. ;)

**Comment by staltz** [comment]
Ok, so why not just use

```js
h('my-custom-element.' + isFocused)
```
?

It is different than `h('my-custom-element' , {className: isFocused})` and does not have the bug.

**Comment by Frikki** [comment]
Sure, I also don’t have any problem using new ES 2015 string syntax.
