### ISSUE TITLE
Nested custom elements

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#35]
Consider these two custom elements.

_custom-element-1_
```javascript
function view(state$) {
  return state$.map(state => {
    const {isFocused, children} = state.props;

    return h(`div.custom-element-1`,
      {className: isFocused ? `isFocused` : ``},
      children
    );
  });
}
```

_custom-element-2_
```javascript
function view(state$) {
  return state$.map(state => {
    const {value} = state;
    const {isFocused} = state.props;

    return h(`div.custom-element-2`,
      [
        h(`custom-element-1`, {isFocused}, [
          h(`input.my-input`, {value}),
        ],
      ]
    );
  });
}
```

_custom-element-2_ uses _custom-element-1_, passing it `isFocused` property and an `INPUT` element as child. _custom-element-1_ uses the passed `isFocused` property to set a class name, and `children` property is used to render the children (the `INPUT` element).

The problem is that the `INPUT` element loses its value when `isFocused` changes, causing _custom-element-1_ to re-render. So my question is, how should I go about this?

**Comment by staltz** [comment]
Have you read about the concept of controlled and uncontrolled form elements? http://facebook.github.io/react/docs/forms.html#controlled-components

Check this gist how I use `ControlledInputHook` as a virtual-dom hook. `null` means "don't touch the value of the input", and not null means to override the value of the input.
https://gist.github.com/staltz/e6fc5b2b19207bb4f7da

**Comment by Frikki** [comment]
Found [this documentation](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md) on hooks for VNodes. I will look into it to see how it can solve my issue.

Thanks for the link to the gist! It is very valuable.
