### ISSUE TITLE
DOM.select() alternative

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#39]
The `DOM.select()` method is using `querySelectorAll()` behind the scenes, which is an operation _99% slower_ than `getElementsByClassName()`.

While `querySelectorAll()` offer a greater flexibility, by far the most times, I use a single class name as selector. In these cases, I would prefer that I could, through `DOM`, use `getElementsByClassName()`. I suggest that an additional method, perhaps `DOM.selectByClassName()`, be added to `DOM`.

Method | Ops/sec<br>chrome / firefox
:------------ | -------------:
``querySelectorAll(`.some-class`)`` | ~262,000 / ~103,000
``getElementsByClassName(`some-class`)`` | ~ 19,714,000 / ~ 975,392,000

[Testing DOM selectors]

**Edits:**
1) Add firefox perfomance results.
2) Add link to tests.

[Testing DOM selectors]: http://jsperf.com/testing-data-atribute-selectors/10

**Comment by staltz** [comment]
Great suggestion. This will be done, but we might need some bikeshedding on the name `selectByClassName()`.

**Comment by Frikki** [comment]
Actually, we could just leave out the extra method and instead do a simple regex to check if `DOM.select()` should use `getElementsByClassName()` when *only a single class name* was passed as *selector*.

```js
const rSingleClassName = /^\.([^ ]*)$/;
const matches = rSingleClassName.exec(selector);
return (matches !== null) ? // single class name
  rootElem.getElementsByClassName(matches[0]) :
  rootElem.querySelectorAll(selector);
```

Above [code should go here].

[code should go here]: https://github.com/cyclejs/cycle-dom/blob/master/src/render-dom.js#L210

**Comment by Frikki** [comment]
Speaking of performance, the code suggested above could be optimized.

```js
return /^\.([^ ]*)$/.test(selector) ? // single class name
  rootElem.getElementsByClassName(selector.substring(1)) :
  rootElem.querySelectorAll(selector);
```

**Comment by Frikki** [comment]
Another thing I just found out, `getElementsByClassName(names)`

> *names* is a string representing the list of class names to match; class names are separated by whitespace

So it becomes somewhat more complicated.

**Comment by staltz** [comment]
Yes, this is just a simple performance optimization it seems:
```js
return /^\.([^ ]*)$/.test(selector) ? // single class name
  rootElem.getElementsByClassName(selector.substring(1)) :
  rootElem.querySelectorAll(selector);
```

But have you checked that regex matching + getElementsByClassName is still faster than querySelectorAll?

**Comment by Frikki** [comment]
Nope, not yet.

**Comment by Frikki** [comment]
This might become too complicated, and I am probably just being too pedantic. Surely, I am not even sure this feature should be considered, unless it proves to actually be a bottleneck.

**Comment by staltz** [comment]
A more important performance bottleneck is the attachment/detachment of event handlers. Currently, on every virtual DOM patch we detach and re-attach all event handlers.

**Comment by Frikki** [comment]
Have you opened an issue on that?

**Comment by staltz** [comment]
This https://github.com/cyclejs/cycle-dom/issues/11

**Comment by Frikki** [comment]
Should we close this?

**Comment by staltz** [comment]
I think we should keep it open. After we get the performance benchmark around, we can toy around and figure out if this proposal speeds up something.

**Comment by Frikki** [comment]
@TylorS Have you got any comments to add to this issue?

**Comment by TylorS** [comment]
Hmm. I'm not sure this is quite as easy to implement nor as needed with event delegation in place.
Reason being `.events()` never uses querySelectorAll(). However `.observable` *does*, but I'm not sure if that's used nearly as often for anything other than testing?

**Comment by Frikki** [comment]
So maybe it’s time to close it? @staltz ?

**Comment by staltz** [comment]
Yeah, we can reopen if it becomes relevant again.
