### ISSUE TITLE
events useCapture

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#41]
The `EventTarget.addEventListener(type, listener[, useCapture])` let’s us specify if we want to initiate capture.

But it does not seem as `Rx.Observable.fromEvent(element, eventName[, selector])`, as [used here in render-dom.js], supports setting the `useCapture` flag. This is, in Web development, a quite important feature to be able access, for example when *focus*, *blur* and *change* events don’t bubble.

[used here in render-dom.js]: https://github.com/cyclejs/cycle-dom/blob/master/src/render-dom.js#L194

**Comment by staltz** [comment]
Can you suggest this change on RxJS? I would build this on Cycle side only if it does not happen in RxJS.

**Comment by Frikki** [comment]
Yes, I can do that. I found this this https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/fromevent.md

**Comment by Frikki** [comment]
Open issue https://github.com/Reactive-Extensions/RxJS/issues/897

**Comment by Frikki** [comment]
I got this answer.

> use RxJS-DOM for useCapture as it makes more sense there with Rx.DOM.fromEvent. Since Rx.Observable.fromEvent is such a flexible event converter, useCapture is only used in one code path as it isn't required for Node.js, Angular, jQuery, etc.
