### ISSUE TITLE
Error with nested custom-elements

### ISSUE THREAD

**Issue by carloslfu** [cyclejs/cycle-dom#50]
When the parent changes the console shows: ```Uncaught Error: Custom element should not have property `children`. It is reserved for children elements nested into this custom element.```

See [this jsbin](http://jsbin.com/fiqalususe/1/edit?js,output).

![image](https://cloud.githubusercontent.com/assets/5993168/10295281/4f4fda7c-6b85-11e5-9e8f-e72c4232a1e6.png)

**Comment by yemi** [comment]
+1

**Comment by joneshf** [comment]
I also had this error, and couldn't figure it out. I ended up getting rid of the custom cycle element, and implementing a custom vdom element directly. If it's time critical, that might be your best bet.

**Comment by staltz** [comment]
I recommend migrating away from custom elements, and using nested components (a cycle.js app inside another cycle.js app). You can find resources on this here http://staltz.com/unidirectional-user-interface-architectures.html, here http://staltz.com/random-namespacing-in-cyclejs.html, and most examples here https://github.com/cyclejs/cycle-examples are already written in this style.

Custom elements will be deprecated, so I don't believe I'll fix this bug. When I do the deprecation, I'll also release migration guides and new documentation.

**Comment by carloslfu** [comment]
Yes, after I found this issue, I've read those articles and started using Nested Dialogs, IMO, this approach looks more elegant and natural than another unidirectional user interface architectures.
