### ISSUE TITLE
fromevent.js causes frame rate drop

### ISSUE THREAD

**Issue by Frikki** [cyclejs/cycle-dom#54]
https://github.com/cyclejs/cycle-dom/blob/master/src/fromevent.js#L37 causes a massive drop in frame rate in the time the script is running (on a fairly decent desktop 7-26 FPS).

Imagine an app, e.g., a game, that requires the user to click a lot on different items; this will cause the whole experience to slow down.

**Comment by Frikki** [comment]
I’ll try to see if I can fix this.

**Comment by staltz** [comment]
Is it because of event listener detachment/reattachment? If so, then we're talking about issue #11

**Comment by Frikki** [comment]
I don’t know yet. I have only looked at the call stack and it’s a lot of Rx.

**Comment by Frikki** [comment]
Okay, so one place that affects this is when actions from `intent()` that use `DOM.select(selector).events(event)` are combined with `props$` in `model()`. The event listeners are created multiple of the Observables combined.

**Comment by Frikki** [comment]
Also, if the DOM element changes signature, e.g., an added class, the event listeners are removed and re-attached.

**Comment by staltz** [comment]
Sounds like #11.

**Comment by staltz** [comment]
We can also consider doing [event delegation like in React](http://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#under-the-hood-autobinding-and-event-delegation) but I'm not excited to have a custom event system above the DOM.

**Comment by Frikki** [comment]
Neither am I, but I am less interested in performance degradation.

**Comment by Frikki** [comment]
However, it might actually prove to increase performance by creating event delegation like React.

**Comment by staltz** [comment]
First let's attempt #11 and then see how bearable performance is.

**Comment by Frikki** [comment]
Agreed.
