### ISSUE TITLE
DOM events should emit values at time of the event?

### ISSUE THREAD

**Issue by YourDeveloperFriend** [cyclejs/cycle-dom#55]
I'm not entirely sure this is a bug, but it was something that had me really confused. You can check out a working js fiddle [here](https://jsfiddle.net/nu68we9h/1/). I have a simple component with a simple enter press action which triggers with the value of the input and only if the value isn't empty:

```javascript
    var DOM = requests.DOM;
    var keyPress$ = DOM.select('.input').events('keypress');
    var enterPress$ = keyPress$
      .filter(ev => ev.keyCode === 13)
      .map(ev => ev.target.value)
      .filter(_.identity);
```

I listen to that event to clear the input on enter press:

```javascript
    var model$ = enterPress$.startWith('');
    var view$ = model$.map(function() {
        return h('input.input', {
          attributes: {
            placeholder: safe ? 'Enter Press Here Triggers' :
              'Enter Press Here Doesn\'t Trigger',
          },
          value: '',
          autofocus: true,
        })
      });

```

I also pass it up to the parent component. The only problem is that the input is being emptied before the value gets emitted to the parent component. So the flow goes like this:

1) Enter gets pressed with the value 'Test'.
2) The keyPress$ observable gets emitted with the event value.
3) The enterPress$ observable gets emitted with the value 'Test'
4) The input gets rendered with an empty value
5) The keyPress$ observable gets emitted with the event value (which now has an empty value)
6) The enterPress$ observable doesn't emit to the parent component, because now the value's empty.

I think this has something to do with hot/cold observables, but I would have thought that the enterPress$ observable would only emit once with the value 'Test', and any subscriptions would run based off that value. Why is enterPress$ making the check twice?

Another Note: I was able to overcome this by putting in a delay on the model$ so that the parent component ran before the input got re-rendered.

**Comment by staltz** [comment]
> I think this has something to do with hot/cold observables

Correct, it does have to do. This works:

```js
var enterPress$ = DOM.select('.input').events('keypress')
      .map(ev => ev)
      .filter(ev => ev.keyCode === 13)
      .map(ev => ev.target.value)
      .share();
```

(By the way, no need for the filter with identity)

**Comment by YourDeveloperFriend** [comment]
Thanks, `share` works!

> (By the way, no need for the filter with identity)

Why? I don't want to emit the event if the value is empty.

**Comment by staltz** [comment]
Then you should filter for truthy. _.identity does that but it's not idiomatic, kind of cryptic.
