### ISSUE TITLE
makeDOMDriver does not handle being called before DOM Ready

### ISSUE THREAD

**Issue by WorldMaker** [cyclejs/cycle-dom#56]
I created a test bundle of all my scripts (using `jspm bundle-sfx` if you are curious, but that shouldn't matter) and when attempting to run as a bundle I hit the case where the browser was running the `makeDOMDriver` function prior to the DOM Ready. (Interestingly the DOM in this case was just the single DIV I'm currently using as a container, so kind of amazing the browsers manage to run the scripts before evaluating the DIV...)

Does it make sense for `makeDOMDriver` to handle the case where it is being called before DOM Ready?

**Comment by staltz** [comment]
Yeah I'll mark this as a bug because makeDOMDriver should indeed start doing its stuff after the DOM is ready, but nothing will change on the API side. You will still call makeDOMDriver whenever you want.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#222
