### ISSUE TITLE
Observables that get passed to wigdets do not get notified of new data

### ISSUE THREAD

**Issue by jisaacks** [cyclejs/cycle-dom#65]
I am using a custom widget. If an Rx observable is passed to that widget from the main view like so:

```javascript
function view(state$) {
  return state$.map((guesses) => {
    return h('div', [
      h('my-custom-widget', {guesses}),
    ]);
  });
}
```

Then my widget will be notified of the initial value coming from the `guesses` observable (and possibly the second value) but then it will just stop. I can manually inspect the observable and see it has the correct values and if I use the observable in the main view it will reflect the new values.

This only happens if the observable is handed to a widget, inside the widget it stops being notified of new values.

If the same observable is defined inside the widget instead of being given the observable then it works. However, that is forcing me to put my business logic into the widget. Is that just the way this is supposed to be? I feel like the widget should not have to deal with business logic. It should just propagate an event stream, and externally that event stream can be modified with business logic.

I am pretty new to Cycle, Rx, and FRP in general, so it is possible that I am just misunderstanding something fundamental.

**Comment by Frikki** [comment]
First, you really shouldn’t use *custom elements*. They are depreciated and will be removed in the next release. The documentation on the Cycle.js website is outdated and is being updated. Instead, you should make *dataflow components*, i.e., a function.

Example:
```js
// replaces custom element
function MyDataflowComponent(sources) {
  // ... do stuff
  return {
    DOM: //... your view
  }
}
```

Also, please join the Gitter chat to get help from the community.
