### ISSUE TITLE
support for observables in svg

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-dom#72]
using observables as children inside svg does currently not work.

Cycle provides it's own `h()` replacing the one of virtual-dom for function for generating vnodes.
The `svg()` function is just a wrapper that delegates to `h()` but cycle does not redefine `svg` and just reexports the definition of virtual-dom. Problem is that the original `svg()` function still calls the original virtual-dom `h()` function instead of the one defined by cycle.

This causes an `UnexpectedVirtualElement` when calling
```javascript
svg('svg', Observable.just(svg('g')))
```

I propose to redefine `svg()` inside cycle to make use of cycle's `h()`.

**Comment by laszlokorte** [comment]
This works for me as a fix:
https://gist.github.com/laszlokorte/f7b52f40d508be5d4027

**Comment by staltz** [comment]
Good catch!

**Comment by laszlokorte** [comment]
I would create a PR containing the code above plus a test case if you like but I am not sure if this is the way you want to handle this or if you prefer another solution to reduce code duplication between cycle and virtual-dom

**Comment by Frikki** [comment]
I think you should make a PR with your solution. Optimization and refactoring can always be done. I feel there’s a need to fix these bugs so Cycle Nested can be shipped.

**Comment by laszlokorte** [comment]
Ok I will to a PR later the day.

**Comment by staltz** [comment]
Cycle Nested wouldn't be blocked from release because of a bug like this (we can always fix bugs after CN is released). What's important for Cycle Nested while it's a release candidate is to try using nested dataflow components and `isolate()` in order to discover potential show-stopper bugs.

**Comment by staltz** [comment]
This is solved in v8.0.0-rc7. Reopen issue if it persists.
