### ISSUE TITLE
dom error reporting

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-dom#73]
Sometimes when working with cycle and something is not working the page just stays blank and no error is logged.

For example the `UnexpectedVirtualElement` error from this issue https://github.com/cyclejs/cycle-dom/issues/72 just got swallowed and it took me a while to track it down.

The reason for this seems to be that rxjs converts errors thrown inside a stream operator into errors emitted on the corresponding stream. The dom driver does not seem to care about all the errors in the streams and just ignores them silently.

I propose to make sure that all errors happening inside the dom streams to be logged in the console. (~~or maybe even better: being converted into a `<div class="cycle-error">message</div>` which get's inserted into the dom~~)

**Comment by Frikki** [comment]
Errors reported to console is maybe a good idea. Inserting DOM nodes is not a good idea, because it presents errors to users in the UI, which is probably not what you want in a production environment.

**Comment by laszlokorte** [comment]
Your are right, console would be best.

**Comment by staltz** [comment]
Totally agree.

**Comment by Cmdv** [comment]
I agree with all this too, I've run into this issue quite a few times when trying to learn.

**Comment by laszlokorte** [comment]
I think adding `.doOnError(console.error.bind(console))` here would do the job:
https://github.com/cyclejs/cycle-dom/blob/auto-scope/src/render-dom.js#L170

Or we could add an error callback parameter to `makeDOMDriver` which defaults to `console.error.bind(console)`

I could create a PR if you like.

**Comment by staltz** [comment]
> I could create a PR if you like.

Would be great!

**Comment by staltz** [comment]
This is solved in v8.0.0-rc7. Reopen issue if it persists.
