### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#8]
_From @kimmobrunfeldt on February 22, 2015 20:42_

What's the browser support for Cycle.js? Sorry if I missed it from docs.

_Copied from original issue: cyclejs/cycle-core#76_

**Comment by staltz** [comment]
It used to be the same as virtual-dom intersection with RxJS, but now with custom elements I am using some things that I'm not quite sure are supported on older browsers. I should put up a compatibility test, but as stated, right now I'm focusing on getting the core API done ASAP, so performance and compatibility and these sort of issues are secondary.

**Comment by staltz** [comment]
_From @kimmobrunfeldt on February 26, 2015 18:9_

If you'd want to automate tests for various real browsers. I would probably go with [BrowserStack](http://www.browserstack.com/). I have used [SauceLabs](https://saucelabs.com/) but browserstack has more browsers and seems a bit better when I gave a look at the tooling.

**Comment by staltz** [comment]
@kimmobrunfeldt
This is now done, browser support is displayed on the README. https://github.com/cyclejs/cycle-dom/blob/master/README.md

**Comment by kimmobrunfeldt** [comment]
Nice! :) :+1:

**Comment by czert** [comment]
What would it take to support ie8 as well? If it's doable in a reasonable way, I'd consider working on it...

**Comment by staltz** [comment]
@czert I don't know, if you want to figure it out, that would be great, but I remember even Microsoft itself doesn't want to support IE8 anymore.

**Comment by czert** [comment]
Well, nobody really wants to support IE8, but some of our clients still demand it :)

I'll see what I can do.
