### ISSUE TITLE
Isolation against children breaks wrapper components

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#80]
Suppose we have a dataflow component `Frame`, which takes some content VTree$ as a child and surrounds that with a painting frame. Then we make the component `Monalisa` which is the painted canvas of Mona Lisa with a frame around it.

`Frame` is a wrapper component.
`Monalisa` is a component that uses the wrapper component.

```js
function Monalisa(sources) {
  const action$ = intent(sources.DOM);
  const state$ = model(action$);

  // View paints the Mona Lisa
  const vtree$ = view(state$);

  const painting = isolate(Frame)({
    DOM: sources.DOM, content$: vtree$,
  });

  return {
    DOM: painting.DOM,
  };
};
```

**Problem:** Monalisa's `intent` is unable to select events happening on Monalisa's own vtree$ created in her `view`, because after `vtree$` is passed as `content$` to the Frame, the Frame takes ownership of that piece of vtree, and the parent (Monalisa) is prohibited from selecting events inside the child's (Frame) vtree. That's because isolation in Cycle DOM currently works like that: it isolates a component against its siblings **and** against its parent.

What should we do? Help @Frikki @TylorS @Widdershin @laszlokorte

Essentially, we want each component to assume: "*If I am a component, I should be able to select (in my intent) events from a vtree I created (in my view).*"

**Comment by staltz** [comment]
This seems like it solves it, but I'm not sure does it feel good to developers:

```diff
 function Monalisa(sources) {
+  const {isolateSource, isolateSink} = sources.DOM;
-  const action$ = intent(sources.DOM);
+  const action$ = intent(isolateSource(sources.DOM, 'please'));
   const state$ = model(action$);
 
   // View paints the Mona Lisa
   const vtree$ = view(state$);
 
   const painting = isolate(Frame)({
-    DOM: sources.DOM, content$: vtree$,
+    DOM: sources.DOM, content$: isolateSink(vtree$, 'please'),
   });
 
   return {
     DOM: painting.DOM,
   };
 };
```

**Comment by laszlokorte** [comment]
After some experiments I got it working like this:
```
function Monalisa(sources) {
+  const {isolateSource, isolateSink} = sources.DOM;
-  const action$ = intent(sources.DOM);
+  const action$ = intent(isolateSource(isolateSource(sources.DOM, 'please'), 'givesomename'));
   const state$ = model(action$);

   // View paints the Mona Lisa
   const vtree$ = view(state$);

-   const painting = isolate(Frame)({
+   const painting = isolate(Frame, 'givemesomename')({
-    DOM: sources.DOM, content$: vtree$,
+    DOM: sources.DOM, content$: isolateSink(vtree$, 'please'),
   });

   return {
     DOM: painting.DOM,
   };
 };
```
The `isolateSource` has be be called twice to satisfy the `isStrictlyInRootScope` check which demands that the whole namespace chain is respected.

But it is late, I am tired and to get this working I had to first fix #81 locally. So it could be that I overlook something.

**Comment by staltz** [comment]
Urgh, doesn't look like an elegant solution, but thanks for finding it anyway. Seems like `isStrictlyInRootScope` needs some tweaking.

I need to come up with the ideal solution which can be easily explained by looking at the solution code, not be knowing `isStrictlyInRootScope` internals.

**Comment by Frikki** [comment]
I see the issue, but I feel that it is the wrong way to use `isolate()`. If `isolate()` is used that way on a component whereto I pass my `vTree$`, I would indeed expect this issue as a result.

**Comment by staltz** [comment]
> From my perspective, it works exactly as intended.

It does work as intended, but then that means we are missing a use case. And a quite common use case that we should support.

**Comment by staltz** [comment]
I just released v8.0.0-rc8 that supports the solution I put in the 2nd comment here.

Core reasoning behind it was:

**Parent-child isolation previously meant: Parent cannot select() anything from child vtree.**

**What we want/need: Parent can select() in a child vtree only from the vtree pieces which the parent originally created, otherwise enforce parent-child isolation.**

**Comment by staltz** [comment]
@laszlokorte since you first experienced this issue, I recommend you to install Cycle DOM 8.0.0-rc8 and see if you can use a solution similar to the Monalisa solution I first posted in this thread. Your feedback is important to me.

**Comment by laszlokorte** [comment]
@staltz rc8 makes your solution working for me. EXCEPT that the `O.just(div(painting.DOM))` is still needed.

**Comment by staltz** [comment]
@laszlokorte that's strange, the test I showed you in #82 should make sure the wrapper div is not needed. From your code, can you extract a minimal reproducible test case? Then I can see if I can solve the bug.

**Comment by laszlokorte** [comment]
The fix for #82 did work in another situation: most outer wrapping div INSIDE monalisa's `view(state$)` is not needed anymore. So that's fine.
But in this case I think 'painting.DOM' needs to be wrapped to prevent it from being isolated twice.
It already has the 'cycle-isolate-1' class added when returned from `isolate(Frame)` and then get's also added the `cycle-isolate-Monalisa` class when returned from `Monalisa` itself (assuming Monalisa itself get's isolated by it's caller.

I will try to extract a minimal test.

**Comment by staltz** [comment]
Ah, I might have an easy fix for that.

**Comment by laszlokorte** [comment]
https://gist.github.com/laszlokorte/e2043a2544184d9aa928

**Comment by staltz** [comment]
Thanks

**Comment by staltz** [comment]
I wasn't able to reproduce @laszlokorte's bug, but I created a test that looks very similar to his code: https://github.com/cyclejs/cycle-dom/blob/2f85a98b6dd200ba8a9bd0758a7678a6b3572743/test/browser/isolation.js#L230

I'll close this issue because it's fixed. Laszlo might still have see some bugs, but at least they aren't show-stoppers, and we can incrementally fix Cycle DOM later on when we find a reproducible test case. First we need to get Cycle Nested out of the door.
