### ISSUE TITLE
isolateSink svg

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-dom#81]
isolateSink does not work with svg elements, because it modifies `vnode.properties.className` but className is not supported by svg nodes.

See:
https://github.com/Matt-Esch/virtual-dom/issues/262
https://github.com/Matt-Esch/virtual-dom/pull/271

Locally I did the following, but there might be a better solutions.
(I am not perfectly sure what exactly are the differences between attributes.class and properties.className inside virtual-dom except that one works for svg and the other does not)
```diff
function isolateSink(sink, scope) {
  return sink.map(function (vtree) {
    var _vtree$properties$className2 = vtree.properties.className;
    var vtreeClass = _vtree$properties$className2 === undefined ? "" : _vtree$properties$className2;

    if (vtreeClass.indexOf("cycle-scope-" + scope) === -1) {
      var c = (vtreeClass + " cycle-scope-" + scope).trim();
      vtree.properties.className = c;
    }

+    if(vtree.properties.attributes) {
+      var _vtree$attributes$class2 = vtree.properties.attributes.class;
+      var vtreeAttrClass = _vtree$attributes$class2 === undefined ? "" : _vtree$attributes$class2;
+
+      if (vtreeAttrClass.indexOf("cycle-scope-" + scope) === -1) {
+        var cattr = (vtreeAttrClass + " cycle-scope-" + scope).trim();
+        vtree.properties.attributes.class = cattr;
+      }
+    }

    return vtree;
  });
}
```
The `if(vtree.properties.attributes)` check is not quite correct because one might want to set the class even if no other attributes have been set.

**Comment by staltz** [comment]
Released version 8.0.0-rc9 with this fixed. Thanks @laszlokorte
