### ISSUE TITLE
select isolated root element

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/cycle-dom#82]
I had not thought about this before but during debugging #80 I got really confused that the following is not working:

```javascript
const view = (state$) =>
  O.just(div('.myClass', 'Hello'))
;

const intent = (DOM) => ({
  click$: DOM.select('.myClass').events('click').map(() => true)
})

const model = (actions) => actions.click$.startWith(false);

const index = () => ({
  DOM: view(model(intent(DOM)))
})

const main = ({DOM}) => ({
  DOM: isolate(index, 'myScope')({DOM}).DOM
})
```

Problem is that the isolation requires the '.myClass' element to be INSIDE the '.cycle-scope-myScope' element.
But the isolation class gets added to the `.myClass` element itself because it is the component's root.

If I want my whole component to be clicked I have to add an additional wrapper element:
```javascript
const view = (state$) =>
  O.just(div(div('.myClass', 'Hello')))
```
I think this is unexpected behavior and should be changed, because if I build my component without isolation in mind it works and if I add isolation later it breaks without any reason I can think of.

Changing this might also get rid of the need for the additional wrapper div mentioned here:
https://github.com/cyclejs/cycle-dom/issues/81#issue-122389008

**Comment by staltz** [comment]
Funny, there is even a test already to support this use case. https://github.com/cyclejs/cycle-dom/blob/auto-scope/test/browser/render.js#L609

Anyway, needs to be fixed.

**Comment by laszlokorte** [comment]
Hm the testcase seems to specify the exact opposite. It allows the parent to access the root of a child. That seems like a mistake. Why would a parent be allowed to access a node which was created by an isolated child component?

**Comment by staltz** [comment]
You might be right, but there is usually a real use case associated to each of these cases.

**Comment by laszlokorte** [comment]
I assumed that :smile: could tell what exact use case that is?

If a parent should actually be able to access an isolated child root element it excludes the child from accessing it's own root because they by definition of isolation a parent and a child should not b able to access the same elements.

Let's say the parent contains the `button('.clickMe')` and one `isolate(childComponent)({DOM}).DOM`.
It binds it's listener on `DOM.select('.clickme')`.
The parent knows nothing about childComponent.
Now childCompontent's DOM is `{DOM: O.just(button('.clickme'))}` and childComponent does also bind on `DOM.select('.clickme')`

Currently the childComponent clicks are not recognized by the childComponent (because .clickme is root) but instead the parent gets the events because `.clickme` class matches. Even though the parent is not supposed to know about the child's `.clickme` class at all.

Currently to fix this you would have to adjust the child by wrapping it `{DOM: O.just(div(button('.clickme')))}`

A better solution would be to inverse the behavior (into "child get's the event parent does not get it").
Then if you have a case in which the parent needs a click event of the childComponent the **parent** should wrap the childComponent.DOM inside an extra div which then can collect the events:
```javascript
{
DOM: div([
button('.clickme'),
button('.clickme'),
div('.inWantChildClicks', [
childComponent({DOM}).DOM
])
])
}
```

**Comment by staltz** [comment]
> I assumed that :smile: could tell what exact use case that is?

I can't remember. I should have written it thoroughly in the commit message. :-1: to me.

I'm favorable of changing it to be what you suggest. It could be one of the examples in cycle-examples depends on this previous behavior, but let's see, and we might be able to rewrite that example.

**Comment by staltz** [comment]
@laszlokorte Can you confirm whether this test is what you expect to happen?

```js
      it('should allow a child component to DOM.select() its own root', function (done) {
        function app(sources) {
          return {
            DOM: Rx.Observable.just(
              h3('.top-most', [
                sources.DOM.isolateSink(Rx.Observable.just(
                  span('.foo', [
                    h4('.bar', 'Wrong')
                  ])
                ), 'ISOLATION')
              ])
            )
          };
        }

        let {sinks, sources} = Cycle.run(app, {
          DOM: makeDOMDriver(createRenderTarget())
        });

        const {isolateSource} = sources.DOM;

        isolateSource(sources.DOM, 'ISOLATION')
          .select('.foo').observable
          .skip(1).take(1)
          .subscribe(function (elements) {
            assert.strictEqual(Array.isArray(elements), true);
            assert.strictEqual(elements.length, 1);
            const correctElement = elements[0];
            assert.notStrictEqual(correctElement, null);
            assert.notStrictEqual(typeof correctElement, 'undefined');
            assert.strictEqual(correctElement.tagName, 'SPAN');
            done();
          });
      });
    });
```

**Comment by laszlokorte** [comment]
@staltz yes that's what I would expect.
