### ISSUE TITLE
Rollup bundler integration and tree-shaking

### ISSUE THREAD

**Issue by arlair** [cyclejs/cycle-dom#83]
I tried to configure the BMI nested example with Rollup instead of Browserify to see how the tree-shaking performed.

Some suggested modifications to Cycle.js were provided here:

https://github.com/rollup/rollup/issues/366

Maybe these are also applicable to Webpack 2 tree-shaking?

Perhaps this is something of interest for Cycle.js?

My attempted repo here:
https://github.com/arlair/cycle-rollup-example

**Comment by staltz** [comment]
Thanks for letting us know.

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#223
