### ISSUE TITLE
Event delegation issues in v8.1.0

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#87]
> I just notices you have implemented event delegation in cycle dom. I did not took a close look yet but I noticed it because 8.1.0 broke my app :smile: I used `event.currentTarget` in various places which now gives me a different element since the listener is bound to the drivers root and not to the element itself. Replacing `currentTarget` with `target` made most of my app working again.
>
> But one problem remains: If I use `DOM.select('.myElement').events('click')` and my markup looks like: `div('.myElement', [div('.someChild', 'Hello'), div('.otherChild', 'world')])` the clicks are not recognized if they are targeted at "Hello" or "World" because then event.target is not `.myElement` but `.someChild` thus is not matched by the `.myElement` selector (But it's parent would match it so the event should be accepted). This concerns all listeners on elements which have child elements. I will take a closer look tomorrow and will create a proper issue. 
>
> I think `event.target` is not affected by the event phase. If I am correct for mouse events `target` is always the deepest node in the tree for which `pointer-events` is not `none`. Capture and Bubble phases happen after `event.target` is already determined.
>
> Currently most (probably even all) of my cases could be fixed by setting `pointer-events` to `none` for all my child elements. But I think the correct way of handling it would be to not only check `evt.target` itself but all it's ancestors at https://github.com/cyclejs/cycle-dom/blob/master/src/render-dom.js#L132-L133
>
> I think jQuery even overwrites the event's currentTarget property during it's event dispatching to make the event delegation mostly transparent from the listeners point of view

```js
it('should have currentTarget pointed to the selected parent', function (done) {
    function app() {
      return {
        DOM: Rx.Observable.just(div('.top', [
          h2('.parent', [
            span('.child', 'Hello world')
          ])
        ]))
      };
    }

    const {sinks, sources} = Cycle.run(app, {
      DOM: makeDOMDriver(createRenderTarget())
    });

    sources.DOM.select('.parent').events('click').subscribe(ev => {
      assert.strictEqual(ev.type, 'click');
      assert.strictEqual(ev.target.tagName, 'SPAN');
      assert.strictEqual(ev.target.className, 'child');
      assert.strictEqual(ev.target.textContent, 'Hello world');
      assert.strictEqual(ev.currentTarget.tagName, 'H2');
      assert.strictEqual(ev.currentTarget.className, 'parent');
      sources.dispose();
      done();
    });
    // Make assertions
    sources.DOM.select(':root').observable.skip(1).take(1).subscribe(function (root) {
      const child = root.querySelector('.child');
      assert.notStrictEqual(child, null);
      assert.notStrictEqual(typeof child, 'undefined');
      assert.strictEqual(child.tagName, 'SPAN');
      assert.strictEqual(child.className, 'child');
      assert.doesNotThrow(function () {
        child.click();
      });
    });
  });
```

Plan:
- [x] Override currentTarget so that it passes the test above
- [x] Automatically set useCapture to true for some whitelisted events: focus, blur, mouseenter, etc.
- [x] Change the API from events(eventType, useCapture) to events(eventType, options)

**Comment by laszlokorte** [comment]
I already posted this in Gitter:
> I just noticed that my mouseenter listener is not working anymore because mouseenter event does not bubble hence is not detected by delegation. Here the solution is to enable capturing. Same goes for focus, blur, submit, mouseenter, mouseleave and load. There should either be a warning that "for the following events you must enable capturing to make them work:..." or capturing should enabled for those events automatically. Or listeners for those events should be bound classically (without delegation) if capturing is not enabled. Or (and I think that might be most straightforward) the delegation should happen via a special method like DOM.select('.myEl').eventsDelegated('click') to emphasize the subtile differences and to give the user the full control over handling edge cases.

Regarding `eventsDelegated` @Cmdv suggested that the naming should be inverted: `events()` doing the delegation and something like `eventsNoDelegate` opting out because most of the time you would want the delegation to happen.

I agree that most of the time you would like to have the delegation but I still think it should be stated explicit because it differs from the standard DOM event handling.

**Comment by Cmdv** [comment]
I'd be quite happy with either or, having the ability/freedom to chose is what would be of importance for me :smile:

**Comment by laszlokorte** [comment]
me in Gitter:
> I think jQuery even overwrites the event's currentTarget property during it's event dispatching to make the event delegation mostly transparent from the listeners point of view

After taking a closer look at the use cases in my application I think it is really important to give the handler function access to the event on which the event was caught. (`currentTarget` in classical event handling)

eg I have a case like this:

```haml
div.tabBar
  div.tab[data-tab-id="1"]
    div.tab-icon
    div.tab-preview
      div.someChild
        ...
      div.moreChild
        ...
    div.tab-label
      First Tab
  div.tab[data-tab-id="2"]
    ...
  div.tab[data-tab-id="3"]
    ....
```

Now I want the tabs to be clicked and I bind a listener like this:
`DOM.select('[data-tab-id]').click().map(evt => ...)`

Depending on if the user clicks on the `.tab-label` or the `.tab-preview` or the `.tab-icon` `evt.target` will be different. Inside the handler I do not care about the exact click target. I wand the element for which I added the listner to fetch the data-tab-id from it. That's what `evt.currentTarget` allows me to access in classical event binding:
`DOM.select('[data-tab-id]').click().map(evt => ({tab: parseInt(evt.currentTarget.dataset.tabId) }))`

Now with event delegation `currentTarget` is always the root element because that's what the listener gets added to. And `target` is to specific. So I no longer have a way to access the element I am interested in. (accept for traversing upwards in the dom tree to look for the matching element myself)

Currently a work around for this is to set `pointer-events: none` for all children of `[data-tab-id]` via css to prevent any event to happen on a child node.

What jQuery does (as far as I know) in it's event delegation is to treat the element to which dom listener is added (the root element) as kind of implementation detail and override the `currentTarget` property of the event object by setting it to the element which matches the selector for which the user asked (`[data-tab-id]`)

**Comment by TylorS** [comment]
I think it would be pretty easy to continue to support the current way things works, but allow for the events that require `useCapture` to automatically set to true.
```
focus, blur, submit, mouseenter, mouseleave and load
```

I was thinking a `DOM.delegate()` method might be a nice way forward. The difference would be that no filtering is applied automatically. So going with the example above `DOM.delegate('[data-tab-id]').events('click')` would attach a click event Listeners to the various data-tab-id nodes and would allow for your own event filtering in whatever way you would choose. I like this idea as it gives you full control over how everything could work. Though I guess it could be argued that this is already possible using `fromEvent()` directly.

Another possible way for it to work, is filtering could be automatically applied for you, but in a slightly different way like the `delegatedEvents()` method above. It could attach the event listener to the root element and automatically check that the events come from a child node of a `data-tab-id` node. Roughly like

```js
rootEl$
  .first()
  .flatMapLatest(rootEl => {
        .........
        return fromEvent(rootEl, eventName, useCapture).filter(ev => {
          const targetNodes = rootEl.querySelectorAll(selector) // 
          const arrayOfTargetNodes = Array.prototype.slice.call(targetNodes)
          return arrayOfTargetNodes.some(t => t.contains(ev.target)) // checks if is a child of targets
        }
   })
```

Though this example doesn't account for namespacing yet, it shows the general idea.

**Comment by laszlokorte** [comment]
As I wrote in Gitter the part about `DOM.delegate('[data-tab-id]').events('click')` seems to be wrong. For one because what you describer is in fact the old behavior which is *not* delegating thus the naming is wrong. Also because I *want* to use delegation (ie common root to which the listener is added only once). So for my case I do not need a way to opt out of delegation. The idea of separating delegation and classical binding was more from a general api point of view.

Your suggestion about filtering the events by checking all `arrayOfTargetNodes` seems to be in the right direction though instead of selecting all possible nodes it might be preferable to just traverse upwards starting from the `event.target` check if any ancestor (inside the isolation boundaries) matches selector

**Comment by staltz** [comment]
@laszlokorte Is this test case what you expect?

```js
  it('should have currentTarget pointed to the selected parent', function (done) {
    function app() {
      return {
        DOM: Rx.Observable.just(div('.top', [
          h2('.parent', [
            span('.child', 'Hello world')
          ])
        ]))
      };
    }

    const {sinks, sources} = Cycle.run(app, {
      DOM: makeDOMDriver(createRenderTarget())
    });

    sources.DOM.select('.parent').events('click').subscribe(ev => {
      assert.strictEqual(ev.type, 'click');
      assert.strictEqual(ev.target.tagName, 'SPAN');
      assert.strictEqual(ev.target.className, 'child');
      assert.strictEqual(ev.target.textContent, 'Hello world');
      assert.strictEqual(ev.currentTarget.tagName, 'H2');
      assert.strictEqual(ev.currentTarget.className, 'parent');
      sources.dispose();
      done();
    });
    // Make assertions
    sources.DOM.select(':root').observable.skip(1).take(1).subscribe(function (root) {
      const child = root.querySelector('.child');
      assert.notStrictEqual(child, null);
      assert.notStrictEqual(typeof child, 'undefined');
      assert.strictEqual(child.tagName, 'SPAN');
      assert.strictEqual(child.className, 'child');
      assert.doesNotThrow(function () {
        child.click();
      });
    });
  });
```

**Comment by TylorS** [comment]
I can confirm that my proposed querySelectorAll() method works, but is terrible on performance. Definitely not the way to go.
https://github.com/TylorS/cycle-dom/tree/feat/child-events/%2387

**Comment by staltz** [comment]
Here is my plan so far:

- **Override `currentTarget` so that it passes the test above**
- **Automatically set `useCapture` to `true` for some whitelisted events**: `focus`, `blur`, `mouseenter`, etc. For all event types that don't bubble, [see this list](https://en.wikipedia.org/wiki/DOM_events#Events).
- **Change the API from `events(eventType, useCapture)` to `events(eventType, options)`** because in the future we might need more arguments to `events()`, and an options object is more explicit than `events('click', true, false, false, true, 5, {}, null, true)` if you know what I mean. Because of automatic `useCapture` to `true` for some whitelisted events (2nd point, above), most users won't ever need to specify `useCapture`, but they can if they wish:

```diff
-select('.foo').events('blur', true)
+select('.foo').events('blur', {useCapture: true})
```
Which will be the same as
```js
select('.foo').events('blur')
```

What do you folks think? CC @Frikki

**Comment by staltz** [comment]
@TylorS I think traversing up from child `target` to parent `currentTarget` might be fairly inexpensive (compared to the querySelectorAll)

**Comment by TylorS** [comment]
Going to test that as well, just figured I'd cover all bases. + :100: on the plans

**Comment by TylorS** [comment]
Whats your plan for overriding the `currentTarget` ? I'm unsure of how to do so in a way that doesn't drain performance.

**Comment by staltz** [comment]
> traversing up from child `target` to parent `currentTarget`

Is the plan...

**Comment by staltz** [comment]
Roughly:

```diff
        return fromEvent(rootEl, eventName, useCapture).filter(ev => {
          if (matchesSelector(ev.target, descendantSelector) ||
              matchesSelector(ev.target, topSelector))
          {
            return isStrictlyInRootScope(ev.target)
          }
          return false
        })
+      .map(ev => {
+        // loop up through the parents, until matchesSelector
+        // set ev.currentTarget to that parent
+      })
```

**Comment by TylorS** [comment]
Shouldn't it replace the current filter? Otherwise most events will never pass through.

**Comment by staltz** [comment]
Ah, right...

**Comment by TylorS** [comment]
ev.currentTarget only has a `getter` by default. Do we really want to override that?

**Comment by staltz** [comment]
:grimacing: what now?

**Comment by TylorS** [comment]
This works, passes all of the tests and is much less expensive than the querySelectorAll() method.
There is no noticeable difference in the rendering. ~2FPS is lost compared to prior.
Only thing is, ev.currentTarget will always be rootElem
```js
return fromEvent(rootEl, eventName, useCapture)
          .filter(ev => {
            for (let el = ev.target; el; el = el.parentElement) {
              if (!isStrictlyInRootScope(el)) {
                break;
              }
              if (matchesSelector(el, descendantSelector) ||
                  matchesSelector(el, topSelector))
              {
                return isStrictlyInRootScope(el)
              }
            }
            return false
          })
      })
```

**Comment by staltz** [comment]
Yeah, that's almost the same code that I wrote, using a different name for "currentTarget", and the test I wrote above passes too:

```js
        return fromEvent(rootEl, eventName, useCapture).filter(ev => {
          const roof = rootEl.parentElement
          for (let el = ev.target; el && el !== roof; el = el.parentElement) {
            if (matchesSelector(el, descendantSelector) ||
                matchesSelector(el, topSelector))
            {
              ev.myCurrentTarget = el
              return isStrictlyInRootScope(el)
            }
          }
          return false
        })
```

**Comment by staltz** [comment]
Well, one option is following jQuery: https://github.com/jquery/jquery/blob/d92310050ca7bf0b33825d64e052f9a8809c3e9e/test/data/jquery-1.9.1.js#L3235

**Comment by TylorS** [comment]
Either we do that globally for performance, or we have to do it locally there every time?

**Comment by staltz** [comment]
How important is `currentTarget`? Can we consider calling it `parentTarget` and leaving `currentTarget` in peace since its readonly? I'm not sure, but I think it's more important that `select('.foo').events('click')` works even when a child of `.foo` is clicked, than to have `currentTarget` correct.

**Comment by TylorS** [comment]
Combining what we both wrote this might be the best performing solution
It avoids going all the way up the tree if its scoped and only calculates `roof` once.
```js
        const roof = rootEl.parentElement
        return fromEvent(rootEl, eventName, useCapture)
          .filter(ev => {
            for (let el = ev.target; el && el !== roof; el = el.parentElement) {
              if (!isStrictlyInRootScope(el)) {
                break;
              }
              if (matchesSelector(el, descendantSelector) ||
                  matchesSelector(el, topSelector))
              {
                return true
              }
            }
            return false
          })
```

**Comment by staltz** [comment]
:+1: Great.

**Comment by TylorS** [comment]
I don't think currentTarget is *that* important. We'll have to what others think. I think it might be confusing though. Up until I started trying to figure this stuff out, I never knew there was a difference between `ev.target` and `ev.currentTarget`

**Comment by TylorS** [comment]
Because up until now, all instances of ev.target and ev.currentTarget have been the same element.

**Comment by staltz** [comment]
Yeah I always knew of the different between `ev.target` and `ev.currentTarget`, except sometimes I got it confused and swapped them around. We have an opportunity to "fix" that confusion by using the name `parentTarget` which is more explicit IMO.

**Comment by staltz** [comment]
It's not the best solution in the world, but the least worse so far.

**Comment by TylorS** [comment]
I can't see any performance change by adding this
```js
Object.defineProperty(ev, 'currentTarget', {
  value: el
})
````

**Comment by TylorS** [comment]
Right before the `return true`

**Comment by TylorS** [comment]
Still seeing ~35FPS on the 1500 slider example.

**Comment by staltz** [comment]
> Still seeing ~35FPS on the 1500 slider example.

In (not Motor) Cycle? That would be good news.

**Comment by TylorS** [comment]
Yes, Cycle, not Motorcycle.

**Comment by staltz** [comment]
And yes, `Object.defineProperty(ev, 'currentTarget', {value: el})` works, thanks for saving the day Tylor.

**Comment by TylorS** [comment]
:+1:

**Comment by TylorS** [comment]
The performance test runs much better than that last time I checked it :smile:

**Comment by staltz** [comment]
Highly relevant since we are doing the same thing: http://info.meteor.com/blog/browser-events-bubbling-capturing-and-delegation

**Comment by staltz** [comment]
@TylorS I also discovered we shouldn't have that test case with a fake non-bubbling click because `ev.initMouseEvent()` is deprecated on the web. I'm having a hard time finding a non-bubbling event which is not focus or blur. Form `submit` is actually refreshing the page since I can't get to preventDefault it soon enough.

**Comment by staltz** [comment]
Nevermind, Form `reset` event worked.

**Comment by Cmdv** [comment]
Sorry dumb question, but would this be the new format then?
`select('.foo').events('blur', {useCapture: true})`

If so, that is pretty clear to me what is happening there

**Comment by TylorS** [comment]
Thanks for the link @staltz 
Glad you were able to get a good test working

**Comment by laszlokorte** [comment]
@staltz yes that test case you asked about is what I would expect.
It seems like you both already got it all working?

**Comment by Frikki** [comment]
@staltz I wouldn’t like any events, not event those that don’t bubble, to default `useCapture: true`, mainly because it is opposite to the real DOM.

Regarding the other issue, `currentTarget`, I need to look more into this to provide an informed opinion.

Another thing, the performance test could probably be enhanced. @TylorS or @laszlokorte had some optimization tricks up the sleeve, as I recall.

**Comment by laszlokorte** [comment]
I agree with @Frikki on `useCapture` for not bubbling events. I think it's bit to much magic to change it's default value depending on the event type.

I am currently not sure what performance test you are talking about?

**Comment by Frikki** [comment]
@laszlokorte The *test/browser/perf*. I believe, you just before the holidays made me aware of how my dynamic component example on Codepen could be optimized, or am I wrong?

**Comment by TylorS** [comment]
I don't think it was me either

**Comment by laszlokorte** [comment]
Oh maybe the virtual-dom Thunk wrapping? That's the only performance related stuff I wrote I can remember?

**Comment by Frikki** [comment]
I cannot remember who it was. But anyway, the test could need a loving hand. I believe the Array-part where the dynamic objects are created could be optimized. @TylorS, I know you know something.

**Comment by TylorS** [comment]
I could probably help it out a bit :)

**Comment by staltz** [comment]
> I wouldn’t like any events, not event those that don’t bubble, to default useCapture: true, mainly because it is opposite to the real DOM.

@Frikki I understand your point of view, but if you consider the perspective of a beginner, the event delegation we are building is transparent, they don't actually know if we are using event delegation or not. Like jQuery and other libraries that use event delegation like Meteor do, I'd like to make it seamless for the beginner: `DOMSource.select('.foo').events('blur')` will give me an Observable of blur events, even if I don't specify useCapture? Why? Because `DOMSource.select('.foo').events('blur', {useCapture: false})` (the default behavior) is entirely useless to the developer, and we don't want to create a *gotcha* just to slow down their productivity.

**Comment by staltz** [comment]
Ok, v9.0.0 is released, but not good. (I think I should start the habit of making canary channels)

Overriding `ev.currentTarget` with Object.defineProperty is making some browsers scream, like Chrome 36, Android browser and iOS browser:
`TypeError: Attempting to configurable attribute of unconfigurable property.`

CC @TylorS

**Comment by laszlokorte** [comment]
I think what jquery and other frameworks do to work around this is creating a a whole custom event object mirroring all (or most?) of the original event's properties.

**Comment by staltz** [comment]
I know, but I'm not so happy about it, sounds too heavy. Right now I'm thinking of mutating `currentTarget` **and** setting `ownerTarget`, both pointing to the same thing, where `ownerTarget` works in all browsers.

**Comment by laszlokorte** [comment]
Maybe you could create a custom object with only the currentTarget property and the original event as prototype? I don't know I will think a bit about it too.

**Comment by staltz** [comment]
By the way, I don't want to blame this on anyone, Tylor was very smart and active in this issue. It's my fault, we need a canary/bleeding-edge channel so people can download Cycle DOM from master and test it around, and release a version (specially a major one) only after a cooldown period.

**Comment by laszlokorte** [comment]
Yes a canary release would be great.

**Comment by TylorS** [comment]
Yeah, that could be very helpful for those who are uncomfortable with pulling everything from github. It'd get more people testing I'm sure.

**Comment by TylorS** [comment]
@staltz I'm looking into the errors too

**Comment by staltz** [comment]
Too late, I fixed them all :dancers:

**Comment by TylorS** [comment]
Well then, what was the solution?

**Comment by staltz** [comment]
> mutating `currentTarget` **and** setting `ownerTarget`, both pointing to the same thing, where `ownerTarget` works in all browsers.

And making all tests pass always in all browsers. Previously I was being slack in letting some browsers fail, but then it meant I never took Travis errors seriously. Now red means really red, and we will now as early as possible. Also it means I dropped official support for IE9, just because we don't yet pass all tests for IE9 (a lot of Cycle.js might still work in IE9), but there is an open issue to get IE9 support better.

**Comment by TylorS** [comment]
:+1: Can't help with IE support though until they decide to support Linux 
Glad we got this mostly all settled for now

**Comment by staltz** [comment]
Yeah I know, thanks @TylorS, no worries. I use Browserstack to check all browsers (highly recommended), but it's not a free product.

**Comment by staltz** [comment]
All done now in v9.0.1
