### ISSUE TITLE
Thunks for optimizing rendering

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-dom#9]
_From @staltz on April 8, 2015 20:34_

This should directly affect performance in the 'many' example.

_Copied from original issue: cyclejs/cycle-core#101_

**Comment by staltz** [comment]
_From @pH200 on May 20, 2015 6:2_

How do you implement thunks when Cycle doesn't have states? `applyToDOM` takes Observable of vtree which is basically the result of rendering. And custom elements are already handling their own subtree redraws.

**Comment by TylorS** [comment]
Not sure if this is still relevant?

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#219
