### ISSUE TITLE
Add support for non-react JSX transformer

### ISSUE THREAD

**Issue by calebmer** [cyclejs/cycle-dom#92]
[`babel-plugin-transform-jsx`](https://www.npmjs.com/package/babel-plugin-transform-jsx) provides a JSX transformation independent of React idiosyncrasies. Could this be supported?

The best way to support this method would be to create a `jsx.js` file which could be accessed like `@cycle/dom/jsx` and recommend people to use `babel-plugin-transform-jsx` with a config of:

```json
{
  "plugins": [["babel-plugin-transform-jsx", { "module": "@cycle/dom/jsx" }]]
}
```

This also has the benefit of removing the need of an `hJSX` in all JSX files.

**Comment by Cmdv** [comment]
I'll start working on a PR for this

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#225
