### ISSUE TITLE
DOM.select() does not properly select an element when it is the root of an isolated vTree.

### ISSUE THREAD

**Issue by TylorS** [cyclejs/cycle-dom#96]
When a *plain* element e.g. `<button />` is used as the root of an isolated vTree DOM.select('button')
is unable to properly select the element and listen for it's events.

An example from @juliomarcos (thank you!)
https://jsbin.com/dadilavoca/edit?js,output

Adding a classname to the button element and using DOM.select('.classname') instead works as expected. 

This does **not** seem to affect DOM.select('button').observable

@laszlokorte mentioned having issues with DOM.select('*') as well which may or may not be related.

**Comment by staltz** [comment]
Thanks for the report

**Comment by TylorS** [comment]
@staltz  This happens because when the namespaces are merged together `['.cycle-scope-1', 'button']` becomes `.cycle-scope-1button` and not `button.cycle-scope-1`

**Comment by laszlokorte** [comment]
I think the issue with `DOM.select('*')` that I came across has the same reason that the selector becomes `.cycle-scope1*` which is not even a valid selector but throws when used with `matches()` or `querySelector()`

**Comment by TylorS** [comment]
Sorting the namespace is one possible solution for both cases of '*' and 'button'
```js
const isValidString = param => typeof param === `string` && param.length > 0
const startsWith = (string, start) => string[0] === start
const isSelector = param =>
    isValidString(param) && (startsWith(param, `.`) || startsWith(param, `#`))

function sortNamespace(a, b) {
  if (isSelector(a) && isSelector(b)) {
    return 0
  }
  return isSelector(a) ? 1 : -1
}
```

Then [here]()

**Comment by laszlokorte** [comment]
Maybe `startsWith(param, ':')` as well to support `:first-child` etc

**Comment by TylorS** [comment]
Good call :+1: 

Do you think that '*' should be a 'selector' ?

**Comment by laszlokorte** [comment]
I think 'selector' is not the best name here because in css terms `button` is a selector too.

There might be some css specification in which order parts of a selector need to be when concatenated.

**Comment by TylorS** [comment]
Good point. I'll try to find something

**Comment by laszlokorte** [comment]
> A sequence of simple selectors is a chain of simple selectors that are not separated by a combinator. It always begins with a **type selector** or a **universal selector**. No other type selector or universal selector is allowed in the sequence.

https://www.w3.org/TR/selectors/#selector-syntax

**type selector**: an element (button, div, a...)
**universal selector**: `*`

So the check could be inverted to test only for `*` and `^[a-z]`

**Comment by TylorS** [comment]
It probably should be inverted there are way more checks for 'selectors' here

**Comment by staltz** [comment]
Looks like you two are quite close to agreeing on a PR

**Comment by tanjucat** [comment]
TylorS says:
> Adding a classname to the button element and using DOM.select('.classname') instead works as expected.

But, as can be seen in the referenced [example](https://github.com/cyclejs/cycle-examples/issues/17), I've seen the problem for `button` even when it is selected using a class name (I tried element id as well).

**Comment by staltz** [comment]
This issue was moved to cyclejs/cycle-core#227
