### ISSUE TITLE
How to subscribe to events without DOM modifications?

### ISSUE THREAD

**Issue by mamciek** [cyclejs/cycle-dom#97]
How can i subscribe events from some dom elements if I do not want to produce changes in DOM?
How can I achive something like this:

```
function main({DOM}) {
   DOM.select('button').events('click').forEach(e => console.log(e))
   return {}
}

run(main, {DOM: makeDOMDriver('#app')})
```
supposing I have html like:
```
<div id="#app">
  <button>Click</button>
</div>
```

Related: https://github.com/motorcyclejs/dom/issues/72

**Comment by staltz** [comment]
Please make questions in the gitter chat or in Stackoverflow :)
